	<footer class="footer">
		<div class="footer__inner">
			<div class="footer__inner__logo__wrap footer__inner__logo__wrap--pc">
				<div class="logo">
					<strong class="hidden">Golden City Gyeongju</strong>
				</div>
			</div>
			<div class="footer__inner__description">
				<p>[38102] 경상북도 경주시 양정로 260 (동천동, 경주시청)</p>
				<p class="copyright">Copyright(C) 2018 Gyeongju-si. All rights reserved.</p>
			</div>
			<div class="footer__inner__logo__wrap footer__inner__logo__wrap--mo">
				<div class="logo">
					<strong class="hidden">Golden City Gyeongju</strong>
				</div>
			</div>
		</div>
	</footer>